# Generated by Django 4.2.10 on 2024-02-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIM7600', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CarOwners',
        ),
    ]
