# Generated by Django 4.2.10 on 2024-03-23 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SIM7600', '0004_alllogs_recentlog_smstask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllogs',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alllogs',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recentlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recentlog',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
